### PR TITLE
Tested on Stretch

### PR DESCRIPTION
**Pull request by stzoran1**
I changed code to meet latest version of Raspbian Stretch and R Pi 3.

### CODE REVIEW

**Comment by sabhiram** [comment]
I apologize for not seeing this PR sooner. Other than a few code format OCD items, all looks good to me. Thank you for testing it on the Pi3. Thank you for comprehending my madness enough to actually get this working w/ `dnsmasq` :)

I will probably give this a whirl on my Pi2 as well just in case (maybe pointless since Pi4s are here).

If you don't mind, could you rebase the 3 commits and squash them into one for the merge?  Once again, much thanks!!

👍

**Comment by sabhiram** [comment]
One other small note - if you dont mind, can we revert the AP name and pwd in `config.json`?

**Comment by stzoran1** [comment]
Sure, I will do that right away.

**Comment by stzoran1** [comment]
Reverted. Please test if you got chance. I noticed that in some cases
password zzzzzzz won't work as it is considered too simple...

**Comment by sabhiram** [comment]
Perfect, thanks for that note - I might just make the password change on master after the merge. Thanks for all the hard work!

**Pull request merged**
